# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'iOS_SuperDuperCrossPlatformCloudGameEngine_Adaptor' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOS_SuperDuperCrossPlatformCloudGameEngine_Adaptor
  pod 'Alamofire', '~> 4.6'
  pod 'SwiftyJSON'

end
